"""Fixtures for MyHOME tests using pytest-homeassistant-custom-component."""
import asyncio
import importlib
import json
import os
import platform
import subprocess
import sys
import warnings

# Python 3.13 compatibility for pytest-homeassistant-custom-component:
# In Python 3.13, HassEventLoopPolicy.get_event_loop() raises RuntimeError when
# the loop is cleared after each test while enable_event_loop_debug autouse fixture
# calls asyncio.get_event_loop().set_debug(True).
try:
    from homeassistant.runner import HassEventLoopPolicy

    _orig_get_event_loop = HassEventLoopPolicy.get_event_loop

    def _safe_get_event_loop(self):
        try:
            return _orig_get_event_loop(self)
        except RuntimeError:
            loop = self.new_event_loop()
            self.set_event_loop(loop)
            return loop

    HassEventLoopPolicy.get_event_loop = _safe_get_event_loop
except ImportError:
    pass

# Ensure required integration dependencies declared in manifest.json are available in CI
if not os.environ.get("OWND_SMOKE_TEST"):
    try:
        import OWNd  # noqa: F401
        from OWNd.message import OWNCenCommand, OWNHeatingCommand, OWNLightingCommand  # noqa: F401
        if not hasattr(OWNHeatingCommand, "central_status"):
            raise AttributeError("central_status not found on OWNHeatingCommand")
        if not hasattr(OWNLightingCommand, "get_hsv_color"):
            raise AttributeError("get_hsv_color not found on OWNLightingCommand")
    except (ImportError, AttributeError):
        installed = False
        if os.environ.get("GITHUB_ACTIONS"):
            branch = os.environ.get("GITHUB_HEAD_REF") or os.environ.get("GITHUB_REF_NAME") or "v2-phase2-architecture"
            for target in [
                f"git+https://github.com/OpenWebNet-HA/OWNd.git@{branch}",
                "git+https://github.com/OpenWebNet-HA/OWNd.git@v2-phase2-architecture",
                "git+https://github.com/OpenWebNet-HA/OWNd.git@master",
            ]:
                try:
                    subprocess.check_call([
                        sys.executable,
                        "-m",
                        "pip",
                        "install",
                        "--upgrade",
                        "--force-reinstall",
                        target,
                    ])
                    installed = True
                    break
                except subprocess.CalledProcessError:
                    continue

        if not installed:
            manifest_path = os.path.join(
                os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                "custom_components",
                "myhome",
                "manifest.json",
            )
            if os.path.exists(manifest_path):
                with open(manifest_path, encoding="utf-8") as f:
                    reqs = json.load(f).get("requirements", [])
                    for req in reqs:
                        subprocess.check_call([sys.executable, "-m", "pip", "install", req])
            else:
                subprocess.check_call([sys.executable, "-m", "pip", "install", "OWNd==2.0.0b5"])
        importlib.invalidate_caches()

        # Clean up any stray coverage data files generated by pip subprocesses
        repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        for f_name in os.listdir(repo_root):
            if f_name == ".coverage" or f_name.startswith(".coverage."):
                try:
                    os.remove(os.path.join(repo_root, f_name))
                except OSError:
                    pass

# Ensure repository custom_components directory is discoverable even when
# pytest-homeassistant-custom-component redirects custom_components package path
try:
    import custom_components
    _repo_cc = os.path.abspath(
        os.path.join(os.path.dirname(os.path.dirname(__file__)), "custom_components")
    )
    if hasattr(custom_components, "__path__") and _repo_cc not in custom_components.__path__:
        custom_components.__path__.insert(0, _repo_cc)
except ImportError:
    pass

import pytest
from homeassistant.core import State
from pytest_homeassistant_custom_component.syrupy import (
    ANY,
    HomeAssistantSnapshotExtension,
    HomeAssistantSnapshotSerializer,
)
from syrupy.assertion import SnapshotAssertion
from syrupy.types import SerializableData

try:
    from aiohttp.web_exceptions import NotAppKeyWarning
    warnings.filterwarnings("ignore", category=NotAppKeyWarning)
except ImportError:
    pass

# This fixture allows us to load custom components in tests
@pytest.fixture(autouse=True)
def auto_enable_custom_integrations(enable_custom_integrations):
    """Enable custom integrations for all tests."""
    try:
        from pytest_socket import enable_socket
        enable_socket()
    except ImportError:
        pass
    yield

@pytest.fixture(autouse=True)
def ignore_third_party_warnings():
    """Ensure third-party aiohttp NotAppKeyWarning does not abort test runs."""
    import warnings
    try:
        from aiohttp.web_exceptions import NotAppKeyWarning
        warnings.filterwarnings("ignore", category=NotAppKeyWarning)
    except ImportError:
        pass
    yield


@pytest.fixture
def event_loop():
    """Create an instance of the default event loop for each test case."""
    try:
        from pytest_socket import enable_socket
        enable_socket()
    except ImportError:
        pass
    policy = asyncio.get_event_loop_policy()
    loop = policy.new_event_loop()
    yield loop
    loop.close()


def pytest_configure(config):
    """Configure pytest to ignore third-party HA dependency warnings."""
    config.addinivalue_line(
        "filterwarnings",
        "ignore::aiohttp.web_exceptions.NotAppKeyWarning",
    )
    config.addinivalue_line(
        "filterwarnings",
        "ignore::DeprecationWarning:homeassistant.*",
    )
    config.addinivalue_line(
        "filterwarnings",
        "ignore::DeprecationWarning:pytest_asyncio.*",
    )
    config.addinivalue_line(
        "filterwarnings",
        "ignore:The event_loop fixture provided by pytest-asyncio.*:DeprecationWarning",
    )
    config.addinivalue_line(
        "filterwarnings",
        "ignore:pytest-asyncio detected an unclosed event loop.*:DeprecationWarning",
    )
    config.addinivalue_line(
        "filterwarnings",
        "ignore::pluggy.PluggyTeardownRaisedWarning",
    )

def pytest_sessionstart(session):
    """Set the event loop policy to Selector on Windows to avoid _ssock AttributeError."""
    if platform.system() == "Windows":
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())


class PatchedHomeAssistantSnapshotSerializer(HomeAssistantSnapshotSerializer):
    """Normalize State snapshots across differing Home Assistant core versions."""

    @classmethod
    def _serializable_state(cls, data: State) -> SerializableData:
        res = super()._serializable_state(data)
        if isinstance(res, dict):
            if "last_reported" not in res:
                res["last_reported"] = ANY
            attrs = res.get("attributes")
            if isinstance(attrs, dict):
                from homeassistant.util.read_only_dict import ReadOnlyDict
                # HA 2026 uses StrEnum attribute keys; snapshots compare the
                # public state names and values, regardless of the key class.
                attrs = ReadOnlyDict({str(key): value for key, value in attrs.items()})
                res["attributes"] = attrs
            if isinstance(attrs, dict) and "supported_features" in attrs:
                feat = attrs["supported_features"]
                if hasattr(feat, "value") and (feat.value & 384) and (feat.value & 1):
                    from homeassistant.components.climate import ClimateEntityFeature
                    from homeassistant.util.read_only_dict import ReadOnlyDict
                    new_attrs = dict(attrs)
                    new_attrs["supported_features"] = ClimateEntityFeature(feat.value & ~384)
                    res["attributes"] = ReadOnlyDict(new_attrs)
        return res


class PatchedHomeAssistantSnapshotExtension(HomeAssistantSnapshotExtension):
    serializer_class = PatchedHomeAssistantSnapshotSerializer


@pytest.fixture
def snapshot(snapshot: SnapshotAssertion) -> SnapshotAssertion:
    """Return snapshot assertion fixture with the Home Assistant extension."""
    return snapshot.use_extension(PatchedHomeAssistantSnapshotExtension)

